import assert from 'assert';
import fs from 'fs';
import path from 'path';
import { backfillCsvFile } from '../analytics/backfill-csv-mae';

console.log('🧪 Testing CSV MAE Backfill functionality...\n');

const sampleCsvPath = path.resolve(__dirname, 'sample_test_analytics.csv');
const enrichedCsvPath = path.resolve(__dirname, 'sample_test_analytics_enriched.csv');

// Mock a sample CSV matching the exact site format generated by buildAnalyticsCSV
const yesterdayIso = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
const exitIso = new Date(Date.now() - 22 * 3600 * 1000).toISOString();

const mockCsvContent = [
  '# ==============================================================================',
  '# MANNA EDGE MARKETS - TRADE ANALYTICS EXPORT',
  '# Scope: Live Session (Client_Delivered)',
  '# Total Trades: 1',
  '# Average MAE: 0.30R',
  '# Average MFE: 2.00R',
  '# ==============================================================================',
  'trade_id,strategy_id,strategy_name,strategy_version,algorithm_version,signal_id,portfolio_name,account_name,account_size_at_entry,symbol,asset_class,exchange,broker,currency,entry_date,entry_time,exit_date,exit_time,entry_timestamp_utc,exit_timestamp_utc,trade_duration_minutes,bars_held,day_of_week,week_number,month,quarter,year,killzone,trading_session,session_open,session_close,opening_range_size,london_open_flag,ny_open_flag,asia_flag,trade_direction,trend_direction,higher_timeframe_bias,market_structure_direction,premium_discount,setup_name,setup_category,entry_pattern,confirmation_pattern,poi_type,liquidity_sweep,fair_value_gap_present,order_block_present,breaker_block_present,mitigation_block_present,imbalance_present,displacement_present,retracement_pct,swing_type,weekly_trend,daily_trend,trend_4h,trend_1h,trend_15m,trend_5m,htf_poi,htf_structure,mtf_structure,ltf_structure,trend_alignment_score,entry_price,initial_stop_price,tp1_price,tp2_price,final_exit_price,highest_price_during_trade,lowest_price_during_trade,maximum_favourable_excursion_mfe,maximum_adverse_excursion_mae,initial_risk_r,risk_pct,risk_usd,position_size,lots_contracts,stop_size_pips,stop_size_points,stop_size_ticks,stop_size_usd,reward_to_tp1,reward_to_tp2,actual_r_multiple,partial_taken,partial_pct,move_to_break_even,time_to_break_even,trailing_stop_used,trailing_stop_type,scale_in,scale_out,manual_close,time_of_manual_close,number_of_management_actions,exit_reason,net_r,gross_profit,gross_loss,net_profit,commission,fees,swap,net_usd,return_pct,conviction_score,checklist_score,risk_quality_score,trend_quality_score,execution_score,entry_quality_score,overall_trade_grade,atr,atr_multiple,volatility_rating,adx,rsi,session_range,news_event_active,high_impact_news_within_30_min,market_regime,liquidity_condition,volume_rating,correlation_score,signal_generated_time,order_submitted_time,order_filled_time,execution_delay_ms,missed_entry_pct,limit_or_market_order,order_modified,requote,client_tagged_count,client_tag_outcome',
  `test_1,manna_snd,Manna SnD,2.0,2.0.0,sig_1,MANNA Core,Institutional,100000,NQ=F,Futures,CME,IBKR,USD,${yesterdayIso.slice(0, 10)},${yesterdayIso.slice(11, 19)},${exitIso.slice(0, 10)},${exitIso.slice(11, 19)},${yesterdayIso},${exitIso},120,120,Tuesday,37,9,3,2026,ny_am,New York,08:00:00,17:00:00,100,0,1,0,LONG,BULLISH,BULLISH,BULLISH,Discount,Manna Supply & Demand Retest,Institutional Order Flow,Order Block Mitigation,Displacement,Order Block,1,1,1,0,1,1,1,61.8,Major,BULLISH,BULLISH,BULLISH,BULLISH,BULLISH,BULLISH,Daily FVG,Bullish Character,Trend Continuation,Lower Breaker,95,29500,29400,29700,29800,29700,,,,0.3,1.0,1.0,1000,2,2,,100,400,1000,2.0,3.0,2.0,1,50,1,15,0,,0,1,0,,2,TP1,2.0,2000,0,2000,4,2.5,0,1993.5,2.0,95,90,95,92,94,91,A,350,1.5,Medium-High,34.5,42.5,530,0,0,Trending,High,Above Average,0.88,${yesterdayIso},${yesterdayIso},${yesterdayIso},120,0,Limit,1,0,0,`
].join('\n');

fs.writeFileSync(sampleCsvPath, mockCsvContent, 'utf8');

(async () => {
  try {
    const result = await backfillCsvFile(sampleCsvPath, enrichedCsvPath, 'manna_snd');
    assert.strictEqual(result.tradesCount, 1, 'Should process 1 trade');

    const enrichedContent = fs.readFileSync(enrichedCsvPath, 'utf8');
    const enrichedLines = enrichedContent.split('\n').filter(l => !l.startsWith('#') && l.trim());
    const headerCols = enrichedLines[0].split(',');
    const dataCols = enrichedLines[1].split(',');

    const maeIdx = headerCols.indexOf('maximum_adverse_excursion_mae');
    const mfeIdx = headerCols.indexOf('maximum_favourable_excursion_mfe');
    const lowestIdx = headerCols.indexOf('lowest_price_during_trade');
    const highestIdx = headerCols.indexOf('highest_price_during_trade');

    console.log('Result MAE in CSV:', dataCols[maeIdx]);
    console.log('Result MFE in CSV:', dataCols[mfeIdx]);
    console.log('Result Lowest Price in CSV:', dataCols[lowestIdx]);
    console.log('Result Highest Price in CSV:', dataCols[highestIdx]);

    assert(dataCols[maeIdx] !== '', 'MAE must not be empty');
    assert(!isNaN(parseFloat(dataCols[maeIdx])), 'MAE must be a valid float');
    assert(parseFloat(dataCols[highestIdx]) > 0, 'Highest price must be populated from candles');
    assert(parseFloat(dataCols[lowestIdx]) > 0, 'Lowest price must be populated from candles');

    console.log('✅ CSV Backfill Test successfully read and filled MAE with real candle data!');
  } finally {
    try { fs.unlinkSync(sampleCsvPath); } catch {}
    try { fs.unlinkSync(enrichedCsvPath); } catch {}
  }
})();
